<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Description>Using POCOs and enums as RPC parameters and return types.</Description>
    <RootNamespace>QueryFarm.VgiRpc.Examples.StructuredTypes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\QueryFarm.VgiRpc\QueryFarm.VgiRpc.csproj" />
  </ItemGroup>

</Project>
